
FROM maven:3.8.5-openjdk-17-slim AS build

WORKDIR /usr/src/mymaven
COPY . .
RUN mvn clean package -DskipTests -X

FROM openjdk:17-slim
WORKDIR /app
COPY --from=build /usr/src/mymaven/target/back-0.0.1-SNAPSHOT.jar ./
EXPOSE 8080
CMD ["java", "-jar", "back-0.0.1-SNAPSHOT.jar"]

