services:
  postgres:
    hostname: postgres
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app_network

  ibmq:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-ibmq
    ports:
      - "1414:1414"
      - "9443:9443"
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: ${MQ_QMGR_NAME}
      MQ_USER: ${MQ_USER}
      MQ_PWD: ${MQ_PWD}
    networks:
      - app_network

  spring:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-spring
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MQ_QMGR_NAME: ${MQ_QMGR_NAME}
      MQ_CHANNEL: ${MQ_CHANNEL}
      MQ_CONN_NAME: ${MQ_CONN_NAME}
      MQ_USER: ${MQ_USER}
      MQ_PWD: ${MQ_PWD}
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - postgres
      - ibmq

networks:
  app_network:
    driver: bridge
